quarkus:
  http:
    test-port: 0
  smallrye-openapi:
    store-schema-directory: openapi
  rest-client:
    todo-api:
      url: http://todo-api-svc:8080

"%dev":
  quarkus:
    rest-client:
      todo-api:
        url: http://localhost:5130